const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Plugins.Mouse,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.NinePatch,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.scrollto,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.Keyboard,
		C3.Behaviors.Turret,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.AddLayer,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.JavaScriptInEvents.Main_Event1_Act24,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.DrawingCanvas.Acts.SetSize,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Behaviors.Physics.Acts.SetLinearDamping,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.DrawingCanvas.Acts.Line,
		C3.Plugins.System.Exps.layertolayerx,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.layertolayery,
		C3.Plugins.Mouse.Cnds.OnRelease,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Exps.right,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Particles.Cnds.OnCreated,
		C3.Plugins.Particles.Acts.SetInitSpeed,
		C3.Plugins.Particles.Acts.SetOpacity,
		C3.Plugins.Particles.Acts.SetGrowRate,
		C3.Plugins.Particles.Acts.SetParticleAcc,
		C3.Plugins.Particles.Acts.SetSpeedRandomiser,
		C3.Plugins.Particles.Acts.SetTimeout,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Exps.BBoxLeft,
		C3.Plugins.Text.Exps.BBoxTop,
		C3.Plugins.Text.Exps.Width,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Exps.Opacity,
		C3.Plugins.Text.Cnds.IsVisible,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.JavaScriptInEvents.Main_Event41_Act1,
		C3.JavaScriptInEvents.Main_Event41_Act2,
		C3.JavaScriptInEvents.Main_Event42_Act1,
		C3.JavaScriptInEvents.Main_Event42_Act2,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Behaviors.Physics.Acts.Teleport,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.NinePatch.Acts.RotateClockwise,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Button.Acts.SetVisible,
		C3.JavaScriptInEvents.Instruct_Event5_Act2,
		C3.JavaScriptInEvents.Instruct_Event5_Act3,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Text.Cnds.CompareText,
		C3.JavaScriptInEvents.Victory_Event8_Act2,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Behaviors.Turret.Acts.SetEnabled,
		C3.Behaviors.Turret.Acts.SetRotate,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.Spawn
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Physics: 0},
	{obj_coll: 0},
	{dummy: 0},
	{obj_ball: 0},
	{Mouse: 0},
	{hovered: 0},
	{originalSize: 0},
	{obj_playbutton: 0},
	{obj_instructionsbutton: 0},
	{ballLineCanvas: 0},
	{obj_sepia_overlay: 0},
	{BackgroundLevel: 0},
	{Flag: 0},
	{obj_wall: 0},
	{Fade: 0},
	{obj_level_complete: 0},
	{targetX: 0},
	{obj_full_background: 0},
	{text_stopwatch: 0},
	{obj_level_end_background: 0},
	{buttonRestart: 0},
	{buttonNext: 0},
	{buttonMenu: 0},
	{text_moves: 0},
	{lvlbackground9patch: 0},
	{offsetY: 0},
	{ScrollTo: 0},
	{obj_ball_follower: 0},
	{obj_death: 0},
	{ball_die_particles: 0},
	{obj_bounce: 0},
	{text_title: 0},
	{obj_text_background: 0},
	{text_debug: 0},
	{Audio: 0},
	{Text_ta_xi_haga: 0},
	{sprexplain: 0},
	{redGUI: 0},
	{instructionsBack: 0},
	{id: 0},
	{Coin: 0},
	{CoinText: 0},
	{coinGUI: 0},
	{Text: 0},
	{ResetProgress: 0},
	{obj_rock: 0},
	{VictoryBack: 0},
	{golden_ball_text: 0},
	{credits: 0},
	{slowBallDownVictoryTrigger: 0},
	{lives_text: 0},
	{heartGUI: 0},
	{Keyboard: 0},
	{thingybingy: 0},
	{Turret: 0},
	{Bullet: 0},
	{triggeroflevel5: 0},
	{Text3: 0},
	{ls: 0},
	{ls2: 0},
	{ls3: 0},
	{ls4: 0},
	{fam_buttons: 0},
	{fam_overlay: 0},
	{startMouseX: 0},
	{startMouseY: 0},
	{opacityOfOverlaySepia: 0},
	{startedDragOnValidArea: 0},
	{allowedToShoot: 0},
	{transitioningFullOverlay: 0},
	{paused: 0},
	{moves: 0},
	{layoutToTransitionTo: 0},
	{levelStartTime: 0},
	{won: 0},
	{fadeOutTitle: 0},
	{powerFactor: 0},
	{CoinsCollected: 0},
	{userInputEnabled: 0},
	{lives: 0},
	{is_golden_ball: 0},
	{layoutToGoToName: 0},
	{sumX: 0},
	{sumY: 0},
	{count: 0},
	{targetY: 0},
	{song: 0},
	{songSpesify: 0},
	{instructionSlideNum: 0}
];

self.InstanceType = {
	Background: class extends self.ISpriteInstance {},
	obj_coll: class extends self.ISpriteInstance {},
	obj_ball: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	obj_playbutton: class extends self.ISpriteInstance {},
	obj_instructionsbutton: class extends self.ISpriteInstance {},
	ballLineCanvas: class extends self.IDrawingCanvasInstance {},
	obj_sepia_overlay: class extends self.ISpriteInstance {},
	BackgroundLevel: class extends self.ISpriteInstance {},
	Flag: class extends self.ISpriteInstance {},
	obj_wall: class extends self.I9PatchInstance {},
	obj_level_complete: class extends self.ISpriteInstance {},
	obj_full_background: class extends self.ISpriteInstance {},
	text_stopwatch: class extends self.ITextInstance {},
	obj_level_end_background: class extends self.ISpriteInstance {},
	buttonRestart: class extends self.ISpriteInstance {},
	buttonNext: class extends self.ISpriteInstance {},
	buttonMenu: class extends self.ISpriteInstance {},
	text_moves: class extends self.ITextInstance {},
	lvlbackground9patch: class extends self.I9PatchInstance {},
	obj_ball_follower: class extends self.ISpriteInstance {},
	obj_death: class extends self.ISpriteInstance {},
	ball_die_particles: class extends self.IParticlesInstance {},
	obj_bounce: class extends self.I9PatchInstance {},
	text_title: class extends self.ITextInstance {},
	obj_text_background: class extends self.ISpriteInstance {},
	text_debug: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Text_ta_xi_haga: class extends self.ITextInstance {},
	sprexplain: class extends self.ISpriteInstance {},
	redGUI: class extends self.ISpriteInstance {},
	instructionsBack: class extends self.I9PatchInstance {},
	Coin: class extends self.ISpriteInstance {},
	CoinText: class extends self.ITextInstance {},
	coinGUI: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	ResetProgress: class extends self.IButtonInstance {},
	obj_rock: class extends self.ISpriteInstance {},
	VictoryBack: class extends self.ISpriteInstance {},
	golden_ball_text: class extends self.ITextInstance {},
	credits: class extends self.ISpriteInstance {},
	slowBallDownVictoryTrigger: class extends self.ISpriteInstance {},
	lives_text: class extends self.ITextInstance {},
	heartGUI: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	thingybingy: class extends self.ISpriteInstance {},
	Turret: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	triggeroflevel5: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	ls: class extends self.ISpriteInstance {},
	ls2: class extends self.ISpriteInstance {},
	ls3: class extends self.ISpriteInstance {},
	ls4: class extends self.ISpriteInstance {},
	fam_buttons: class extends self.ISpriteInstance {},
	fam_overlay: class extends self.ISpriteInstance {}
}